spring.application.name=green-pages 
spring.datasource.url=jdbc:postgresql://localhost:5432/olge_green_pages
spring.datasource.username=ernarmyrzabek
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect